version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=t_finance
      - POSTGRES_USER=juanespinola
      - POSTGRES_PASSWORD=juanespinolapassword
    ports:
      - 5432:5432
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
